import dayOne from './solutions/1.js';
import dayTwo from './solutions/2.js';
import dayThree from './solutions/3.js';
import dayFour from './solutions/4.js';
import dayFive from './solutions/5.js';
import daySix from './solutions/6.js';
import daySeven from './solutions/7.js';
import dayEight from './solutions/8.js';
import dayNine from './solutions/9.js';
// import dayTen from './solutions/10.js';
// import dayEleven from './solutions/11.js';
// import dayTwelve from './solutions/12.js';
// import dayThirteen from './solutions/13.js';
// import dayFourteen from './solutions/14.js';
// import dayFifteen from './solutions/15.js';
// import daySixteen from './solutions/16.js';
// import daySeventeen from './solutions/17.js';
// import dayEighteen from './solutions/18.js';
// import dayNineteen from './solutions/19.js';
// import dayTwenty from './solutions/20.js';
// import dayTwentyOne from './solutions/21.js';
// import dayTwentyTwo from './solutions/22.js';
// import dayTwentyThree from './solutions/23.js';
// import dayTwentyFour from './solutions/24.js';
// import dayTwentyFive from './solutions/25.js';

// dayOne();
// dayTwo();
// dayThree();
// dayFour();
// dayFive();
// daySix();
// daySeven();
// dayEight();
dayNine();
// dayTen();
// dayEleven();
// dayTwelve();
// dayThirteen();
// dayFourteen();
// dayFifteen();
// daySixteen();
// daySeventeen();
// dayEighteen();
// dayNineteen();
// dayTwenty();
// dayTwentyOne();
// dayTwentyTwo();
// dayTwentyThree();
// dayTwentyFour();
// dayTwentyFive();
