import dayOne from './solutions/1.js';
import dayTen from './solutions/10.js';
import dayEleven from './solutions/11.js';
import dayTwelve from './solutions/12.js';
import dayTwo from './solutions/2.js';
import dayThree from './solutions/3.js';
import dayFour from './solutions/4.js';
import dayFive from './solutions/5.js';
import daySix from './solutions/6.js';
import daySeven from './solutions/7.js';
import dayEight from './solutions/8.js';
import dayNine from './solutions/9.js';

// dayOne();
// dayTwo();
// dayThree();
// dayFour();
// dayFive();
// daySix();
// daySeven();
// dayEight();
// dayNine();
// dayTen();
// dayEleven();
dayTwelve();
